<?php

/**
 * WP Post REST
 * Plugin Name: WP Post REST
 * Plugin URI: https://github.com/dknieriem/wp-post-rest
 * Description: A WordPress plugin that creates a REST endpoint to retrieve post information
 * Version: 1.0.0
 * Author: Don Knieriem
 * Author URI: https://github.com/dknieriem
 */

 /**
 * REST Callback function that wraps data in a rest response
 */
function  wp_post_rest_get_endpoint( $request ) {
  $numPosts = is_numeric($request['numPosts']) && $request['numPosts'] > 0 ? $request['numPosts'] : 10;
  // rest_ensure_response() wraps the data we want to return into a WP_REST_Response, and ensures it will be properly returned.
  return rest_ensure_response( wp_post_rest_get_posts($numPosts) );
}

/** 
 * Function to load # of most recent posts 
 * Returns array w/ 'posts' and 'size' keys
 */
function wp_post_rest_get_posts($numPosts) {

  $posts = wp_get_recent_posts($numPosts);
  // No filtering needed, just use the methods given!
  return [
    'posts' => $posts, 
    'size' => sizeof($posts)
  ];
}

/**
* Register route per https://developer.wordpress.org/plugins/routes-endpoints/
*/
function wp_post_rest_register_routes() {
  register_rest_route( 'wp-post-rest/v1', '/getposts/(?P<numPosts>\d+)', array(
      'methods'  => WP_REST_Server::READABLE,
      'callback' => 'wp_post_rest_get_endpoint',
  ) );
}

add_action( 'rest_api_init', 'wp_post_rest_register_routes' );


/** Generate dummy posts to demonstrate plugin */
function wp_post_rest_activate_plugin() {
  for( $postNum = 0; $postNum < 25; $postNum++) {
    wp_post_rest_generate_post($postNum);  
  }
}

/** Generate the nth fake post */
function wp_post_rest_generate_post($postNum) {
  $postarr = [
    'post_content' => __("This is the no. {$postNum} post generated by the wp_post_rest module for testing!"),
    'post_title' => __("Generated post {$postNum}"),
    'post_status' => 'publish',
  ];

  $postID = wp_insert_post($postarr);
}

register_activation_hook(
  __FILE__,
  'wp_post_rest_activate_plugin'
);